export const countryNames: Record<string, string> = {
    BR: 'Brasil',
    US: 'Estados Unidos',
    PT: 'Portugal',
    AR: 'Argentina',
    CL: 'Chile',
    UY: 'Uruguai',
    PY: 'Paraguai',
    CO: 'Colômbia',
    PE: 'Peru',
    MX: 'México',
    CA: 'Canadá',
    GB: 'Reino Unido',
    FR: 'França',
    DE: 'Alemanha',
    IT: 'Itália',
    ES: 'Espanha',
    JP: 'Japão',
    CN: 'China',
    AU: 'Austrália',
    IE: 'Irlanda',
}